### ISSUE TITLE
Handle Donation Received Event 

### ISSUE THREAD

**Issue by Oshioke-Salaki** [Token-Giver/token-giver-backend#1]
Create a service to handle the "donation received" event emitted from the blockchain. Update the donation amount for the corresponding campaign in the database. 

Acceptance Criteria: 
- Implement handleDonationReceivedEvent to process the event.
- Extract donation details from the event.
- Use Prisma to update the campaign's donation total.
- Log the event processing success or errors.

**Comment by Jemiiah** [comment]
I would love to work on this issue

**Comment by Unickhub** [comment]
well this will be really cool

**Comment by hannahredler** [comment]
Hey! Im a full stack dev, with a few years of experience in web3, although fairly new to Cairo. I would appreciate the chance to work on this task!

I would work through the acceptance criteria as stated, ensuring the logs and events are emitted correctly.

**Comment by CollinsC1O** [comment]
Hello I'm a front-end and a blockchain developer I did love to handle this task?

**Comment by ShantelPeters** [comment]
Can I contribute to this one?

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have already seen project code and understard  .   please /assign  this issue .
Thank You

**Comment by shaaibu7** [comment]
I am a backend developer with experience building scalable back-end systems.

This is how i would go about handling this task.

Listen to Blockchain Events: listen for the DonationReceived event emitted by the smart contract.

Extract Event Data: When the event is detected, extract the donation amount from the event data.

Update the Database: Use Prisma to update the totalDonations field in the corresponding campaign record in the database.

Log Success or Errors: Log the success or failure of the database update for debugging and monitoring purposes.

Service Setup: Initialize the event listener on application startup to ensure events are captured in real time.
