### ISSUE TITLE
refac: refactor handle donation event

### ISSUE THREAD

**Issue by EjembiEmmanuel** [Token-Giver/token-giver-backend#15]
**Description:**

Transfer the current logic for handling donation events in `src/donation.service.ts` to `src/token-giver-indexer/token-giver-indexer.service.ts`. See `handleCampaignCreatedEvent` function in  `src/token-giver-indexer/token-giver-indexer.service.ts` for a reference implementation.

`DontationCreated`event
```
#[derive(Drop, starknet::Event)]
  pub struct DonationCreated {
      #[key]
      campaign_id: u256,
      #[key]
      donor_address: ContractAddress,
      amount: u256,
      token_id: u256,
      block_timestamp: u64,
  }
```

**Comment by ryzen-xp** [comment]
Hi there!
 I’m a blockchain developer with experience in Cairo, Rust, Solidity, typescript  and web development. I’ve contributed to projects like Chainevents and Arkprojects,sunshine  and I’m excited to bring that experience here.
Refactoring the donation handling logic sounds like an excellent match for my skills. Could you please assign this issue to me?
Thank you!

**Comment by beeguy74** [comment]
Hi, I am a beginner Cairo developer from Paris.
Closed 2 tasks on cairo on 10 ODHACK.
I am very interested it will be a great challenge for me to solve this issue for you.
I don't promise to finish the issue quickly because your project is new to me =)
But I intend to do a decent job and at least do the draft PR within 48 hours.
Could I try solving this?

**Comment by beeguy74** [comment]
Hi, I am a beginner Cairo developer from Paris. 
Closed 2 tasks on cairo on 10 ODHACK. 
I don't promise to finish the issue quickly because your project is new to me =)
But I intend to do a decent job and at least do the draft PR within 48 hours.
Could I try solving this?
May I handle this issue?

**Comment by jaykayudo** [comment]
Could I be assigned to this?

**Comment by mimisavage** [comment]
I'd be happy to do this.

**Comment by Supa-mega** [comment]
Is it okay if I tackle this?

**Comment by No-bodyq** [comment]
I'd like to handle this task.

**Comment by Joewizy** [comment]
Can I take this issue?

**Comment by Iwueseiter** [comment]
Can I be assigned to this?
I'm a frontend and smart contract developer. I will refactor this handle donation event as expected. looking forward to working on this.

**Comment by mimiprosper** [comment]
I would like to take this task. Am a web 2 frontend developer, a technical writer, a solidity smart contract developer/auditor and a cairo smart contract developer. Am a graduate of Starknet Cairo Bootcamp. I have successfully done tasks assigned to me in OnlyDust. 
If assigned this i would complete it within 2 days. 

Here are some articles i have written: https://medium.com/@emma.onyedika.okeke

**Comment by shaaibu7** [comment]
Hello,

I am backend and smart contract developer and would love to work on this issue.

I would migrate the handle donation recieved from `src/donation.service.ts` to `src/token-giver-indexer/token-giver-indexer.service.ts`.

**Comment by jedstroke** [comment]
Can I handle this task?

**Comment by shaaibu7** [comment]
Hello,

I am backend and smart contract developer and would love to work on this issue.

I would migrate the handle donation recieved from `src/donation.service.ts` to `src/token-giver-indexer/token-giver-indexer.service.ts`.

**Comment by GideonBature** [comment]
Could I grab this task?

My name is Gideon Bature, a Software Engineer, I have experience working with Cairo, refactoring and making sure all components still works. If given the opportunity, I will send my first PR within 72 hours.

Thank you!

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by ShantelPeters** [comment]
Can I take this from here?

**Comment by Amarjeet325** [comment]
Can I take care of this issue?

**Comment by Jagadeeshftw** [comment]
Hello, I’d love to work on this issue as I have strong experience in developing secure and efficient smart contracts using Cairo and deploying them on StarkNet. Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by suhas-sensei** [comment]
Can I attempt this issue? "I'll migrate the donation event handling logic to the token-giver-indexer service, implementing handleDonationCreatedEvent to process the donation data (campaign_id, donor_address, amount, token_id) and update records using Prisma. 
Having experience with service refactoring and event processing, I'll ensure clean code migration while maintaining existing functionality.

**Comment by Kingsuite** [comment]
Can I take this from here?

**Comment by Kingsuite** [comment]
Can I take this from here?

I am a backend developer and will love to handle this task. It will be  a great delight to contribute to this awesome project. 
Looking forward to you assigning me
