### ISSUE TITLE
feat: Handle `DeployedTokenGiverNft` event

### ISSUE THREAD

**Issue by EjembiEmmanuel** [Token-Giver/token-giver-backend#17]
**Description:**

Implement function to handle the `DeployedTokenGiverNFT` event emitted from the contract. Parse the event data and use Prisma to update  the campaign in the database.

**Acceptance Criteria:**

- Implement `handleDeployedTokenGiverNftEvent` in `src/token-giver-indexer/token-giver-indexer.service.ts` to process event data.
- Extract relevant campaign details from the event.
- Use Prisma to update the campaign record in the database.
- Log the event processing success or any errors.

`DeployedTokenGiverNFT` event
```
#[derive(Drop, starknet::Event)]
  pub struct DeployedTokenGiverNFT {
      pub campaign_id: u256,
      pub token_giver_nft_contract_address: ContractAddress,
      pub block_timestamp: u64,
  }
```

**Comment by codebestia** [comment]
Can i tackle this?
I am blockchain developer with adequate experience in building blockchain application for several chains. I expertise mainly with rust, cairo and solidity but i still dabble with trending technologies.

## How i will handle this task?
- I will follow the above description 
- I will open a PR as soon as possible

**Comment by No-bodyq** [comment]
Can I work on this, please?

**Comment by Emmanex01** [comment]
Can I take this issue?

**Comment by Akshola00** [comment]
Hello, I'm Akinshola Akinniyi, a backend developer with experience in working with smart contracts and integrating them with databases using Prisma. I have contributed to various projects, focusing on event handling, data parsing, and ensuring smooth integration between blockchain events and backend systems.

I would love to take on the task of implementing the event function. With my experience in working with  events, I’m confident I can efficiently extract the necessary campaign details from the event and update the database accordingly. I will also ensure proper logging of the process for both successes and errors. Please assign me this task—I’m eager to contribute to the project!

**Comment by Supa-mega** [comment]
Can I contribute to this one?

**Comment by jedstroke** [comment]
Could I take a shot at this?

**Comment by anonfedora** [comment]
I'm Eleazar a fullstack blockchain devloper, proficient in Cairo, Nestjs, Nextjs, Expressjs.

Will implement the token-giver-indexer service to process event data, extract relevant campaign details from the event, update the campaign record in the database and log event processing success or any errors encounted.

**Comment by Joewizy** [comment]
I’d like to resolve this. I am an experience blockchain developer that has worked with tons of project I would love to tackle this issue.
I would setup an event listener to get the relevant details of the event generated from the smart contract and then update the database using Prisma and lastly handle events for success and failure.

**Comment by shaaibu7** [comment]
Hello,

I am backend and smart contract developer and would love to work on this issue.

I would write a function to listen for DeployedTokenGiverNFT event when it is emitted and extracts the event details to store in the database using prisma.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by ShantelPeters** [comment]
Can I take care of this issue?

**Comment by Amarjeet325** [comment]
Can I take care of this issue?

**Comment by Amarjeet325** [comment]
Can I take care of this issue?

**Comment by suhas-sensei** [comment]
Can I work on this, please? I'll implement the handleDeployedTokenGiverNftEvent function to process DeployedTokenGiverNFT events, extract campaign_id and contract address data, and update campaign records via Prisma.
Having worked with event indexing and database updates, I'll ensure proper error handling and logging while maintaining data consistency.

**Comment by tasneemtoolba** [comment]
can I take this issue? trying to gain more experience in web3! I'm a full-stack developer!)

**Comment by Pvsaint** [comment]
Can I contribute to this one? I'm a front-end and smart contract developer and I'd love to help with this issue.

**Comment by ikezuby2012** [comment]
Hello, my name is nnubia nzube, I'm a full-stack developer with nearly 4 years of experience working with JavaScript, TypeScript, Reactjs, Nextjs, tailwindcss, Express.js, and recently exploring Cairo for blockchain development. I’m passionate about building robust and scalable applications while ensuring clean and maintainable code.

i would like to work on this issue

**Comment by DuendexCR** [comment]
I’d like to help with this.

**Comment by olisaagbafor** [comment]
I’d like to resolve this.
