### ISSUE TITLE
Test: Test `handleCampaignCreatedEvent` Function

### ISSUE THREAD

**Issue by EjembiEmmanuel** [Token-Giver/token-giver-backend#18]
**Description**

Write unit tests for the `handleCampaignCreatedEvent` function to ensure it correctly processes `CreateCampaign` events and stores data in the database.

**Tasks**

**1. Unit Tests:**

- Mock `prismaService` and validate correct calls with valid and invalid event data.
- Test error handling for invalid addresses or token IDs.

**2. Integration Tests:**
- Verify database insertion with test database and realistic event payloads.

**3. Edge Cases:**
- Test null/undefined event values and Prisma errors.

**Comment by tasneemtoolba** [comment]
can I take this issue? trying to gain more experience in web3! I'm a full-stack developer!)

**Comment by OkoliEvans** [comment]
Can I take on this issue? I have experience building backend applications and testing

**Comment by MullerTheScientist** [comment]
I'd love to address this task

**Comment by Mystic-Nayy** [comment]
Let me try this one!
I am a web3 developer, I can do this effortlessly If you assign me 
I will Write  the unit tests for the handleCampaignCreatedEvent and ensure it is correctly written and tested.

**Comment by Supa-mega** [comment]
Could I take over this issue?

**Comment by jedstroke** [comment]
I'd like to handle this task.

**Comment by ikemHood** [comment]
I am Ikem Peter a software developer with 3+ years of expierence
I would love to tackle this issue,
I would write unit and integration test cases to test `handleCampaignCreatedEvent` functions
EDT: 24hrs

**Comment by coxmars** [comment]
I'm a software developer with 2+ years of experience and I have worked with backend technologies such as Cairo, Java, C# and frontend with React, NextJS, JS/TS. Also, I'm a member of the Dojo Coding community here in CR and I have made contributions in Cairo VM Go, Cairo VM TS, Cairo Lints etc. Likewise, I’m a Cairo developer working in ByteBuildersLabs creating on-chain games using the Dojo framework.

This is my approach:

1- I will review the project structure to place the tests and other parts as expected.
2- I’m going to use the code structure/best practices implemented among the project codebase to continue the standard
3- I'm going to add the unit tests passing >= 70 % code coverage.

I implemented tests here: https://github.com/ArkProjectNFTs/ark-market/pull/181

ET: 3 days

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by tamaraantonella** [comment]
May I take care of this?

**Comment by Amarjeet325** [comment]
Can I take care of this issue?

**Comment by MarcusDavidG** [comment]
I'd like to take this issue.

**Comment by mimisavage** [comment]
I’d like to resolve this.

**Comment by vestor-dev** [comment]
Ihey sir i would love to work on this issue 
i'm a blockchain dev and i would love to handle this issue 
assign me and i'll get to work

ETA: 48hrs

**Comment by Jagadeeshftw** [comment]
Hello, I’d love to work on this issue as I have strong experience in developing secure and efficient smart contracts using Cairo and deploying them on StarkNet. Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by suhas-sensei** [comment]
Let me handle this issue! I'll implement comprehensive tests for handleCampaignCreatedEvent, focusing on unit tests with mocked prismaService and integration tests with a test database.
Having experience with event handling and Prisma testing, I'll ensure thorough coverage of success cases, error handling, and edge cases.

**Comment by nonso7** [comment]
Is it okay if I tackle this?

**Comment by caxtonacollins** [comment]
Could I take on this issue?

**Comment by DuendexCR** [comment]
Could I be assigned to this?

**Comment by olisaagbafor** [comment]
Could I be assigned to this?

**Comment by GideonBature** [comment]
I’d like to resolve this.

My name is Gideon Bature, a Software Engineer with experience building and testing web applications in JavaScript/TypeScript using prisma also for database. I will love to contribute to this project and if given the opportunity, I should send my first PR within 72 hours.

Thank you!

**Comment by Ekene001** [comment]
Hello I'm Ekene, a frontend and blockchain developer, and I’m new to the OnlyDust platform. This is my first time contributing to this repository, and I’m excited about the opportunity to collaborate and bring my skills to the table. 

Here's how i'll tackle this task:

I’ll write unit tests to ensure the handleCampaignCreatedEvent function processes events and calls prismaService correctly for valid and invalid data. I’ll also test error handling for invalid addresses or token IDs.

Next, I’ll run integration tests using a test database to verify data is stored properly with realistic event payloads. Finally, I’ll cover edge cases like null values and Prisma errors to ensure the function handles all scenarios smoothly.

**Comment by kayceeDev** [comment]
I’d like to help with this.

I have solid experience in Unit testing as well as integration tests.
I will also use my proficient backend and typescript skills to make sure all test cases are covered with 100% coverage. I will also write falling test to make sure the function behaves as expected.

My open source contribution skills will help me create the PR as expected.

Please assign me
