### ISSUE TITLE
Handle Campaign Updated Event

### ISSUE THREAD

**Issue by Oshioke-Salaki** [Token-Giver/token-giver-backend#2]
Create a service to handle the "CampaignUpdated" event emitted from the contract. Parse the event data and use Prisma to update the campaign in the database. 

Acceptance Criteria: 
- Implement handleCampaignUpdatedEvent to process the event.
- Extract campaign update details from the event.
- Use Prisma to update the campaign record in the database.
- Log the event processing success or errors.

**Comment by ooochoche** [comment]
Let me try this one!

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by hannahredler** [comment]
Hey! Im a full stack dev, with a few years of experience in web3, although fairly new to Cairo. I would appreciate the chance to work on this task!

**Comment by ooochoche** [comment]
I would love to work on this. I will approach this issue by:

- Understanding the "CampaignUpdated" event structure** from the smart contract.  
- Setting up an event listener** using `ethers.js` or `web3.js`.  
- Parsing the event data** and extract relevant details (e.g., `campaignId`, `updates`).  
- Using Prisma to update the database** with the extracted data.  
- Testing the service** with unit and integration tests.  
- Deploying and monitor the service** in your chosen environment.

**Comment by Kom02** [comment]
Hi, My name is Kevin Obando, a full stack junior developer with 2 years of experience from Costa Rica. I am starting in this community and I want to help in this project.

**Comment by Oshioke-Salaki** [comment]
gm @ooochoche what is the update on this? I need a PR in the next 24hrs or i'd have to reassign.

**Comment by ooochoche** [comment]
@Oshioke-Salaki I am on it
