### ISSUE TITLE
Handle Campaign Created Event

### ISSUE THREAD

**Issue by Oshioke-Salaki** [Token-Giver/token-giver-backend#3]
Create a service to handle the "CampaignCreated" event emitted from the contract. Parse the event data and use Prisma to store the new campaign in the database. 

Acceptance Criteria: 
- Implement handleCampaignCreatedEvent to process event data. 
- Extract relevant campaign details from the event. 
- Use Prisma to create a new campaign record in the database. 
- Log the event processing success or any errors.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev kindly assign :)

**Comment by Jemiiah** [comment]
hello please i would love to work on this issue

**Comment by MrRoudyk** [comment]
Can I tackle this one?

**Comment by morelucks** [comment]
I'd love to work on this!

**Comment by mimiprosper** [comment]
Could I try solving this?  Am a web 2 frontend developer, a solidity smart contract developer/auditor and a cairo smart contract developer. Am a graduate of Starknet Cairo Bootcamp. I have successfully done tasks assigned to me in OnlyDust. If assigned this i would complete it within 2 days.

**Comment by Oshioke-Salaki** [comment]
gm @manoahLinks  what is the update on this?
