### ISSUE TITLE
Create GraphQL Resolver to Fetch Campaign by ID

### ISSUE THREAD

**Issue by Oshioke-Salaki** [Token-Giver/token-giver-backend#4]
Create a GraphQL resolver to fetch a specific campaign by its unique ID. Validate the ID, query the database using Prisma, and return the corresponding campaign or an error if not found.

Acceptance Criteria:
- Define a resolver method getCampaignById(id: string) in CampaignResolver.
- Validate the provided ID.
- Query the database using Prisma to fetch the campaign.
- Return the campaign data or handle cases where it does not exist.

**Comment by JoE11-y** [comment]
Can I be assigned to this?

**Comment by ShantelPeters** [comment]
Could I try solving this?

**Comment by Kom02** [comment]
Hi, My name is Kevin Obando, a full stack junior developer with 2 years of experience from Costa Rica. I am starting in this community and I want to help in this project.
