### ISSUE TITLE
Create GraphQL Resolver to Fetch All Campaigns

### ISSUE THREAD

**Issue by Oshioke-Salaki** [Token-Giver/token-giver-backend#5]
Create a GraphQL resolver to retrieve all campaigns from the database. Use Prisma for database queries and return the list of campaigns through the GraphQL API.

Acceptance Criteria:
- Define a resolver method getAllCampaigns() in CampaignResolver.
- Use Prisma to query the database for all campaigns.
- Return the list of campaigns as a GraphQL query result.
- Implement error handling for database query failures.

**Comment by ikemHood** [comment]
May I take care of this?

**Comment by ShantelPeters** [comment]
Would love to tackle this!

**Comment by Kom02** [comment]
Hi, My name is Kevin Obando, a full stack junior developer with 2 years of experience from Costa Rica. I am starting in this community and I want to help in this project.

**Comment by morelucks** [comment]
I'd like to handle this task.

**Comment by ikemHood** [comment]
I'd like to work on this @Oshioke-Salaki, EDT: 4hrs.

**Comment by Kom02** [comment]
Hi, My name is Kevin Obando, a full stack junior developer with 2 years of experience from Costa Rica. I am starting in this community and I want to help in this project.

**Comment by Supa-mega** [comment]
I’m interested in this one.

**Comment by jedstroke** [comment]
Can I work on this, please?

**Comment by Kaminar-i** [comment]
Could I take on this issue?

**Comment by suhas-sensei** [comment]
I'd be happy to do this. I have some experience in creating with graphql tho i would have to learn how to use prisma

**Comment by blessingbytes** [comment]
I am a frontend and blockchain developer specializing in creating intuitive user interfaces. pls i would love to tackle this issue

**Comment by 0xdevcollins** [comment]
May I take this issue on?

My Background
I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 46 significant contributions spread over 12 OnlyDust projects.

**Comment by suhas-sensei** [comment]
thank you for the assignment.

**Comment by Oshioke-Salaki** [comment]
gm @suhas-sensei what is the update on this? I need a PR in the next 24hrs or i'd have to reassign.

**Comment by suhas-sensei** [comment]
sure ser
